<?xml version='1.1' encoding='UTF-8'?>
<build>
  <actions>
    <hudson.model.ParametersAction>
      <safeParameters class="sorted-set"/>
      <parameters>
        <hudson.model.StringParameterValue>
          <name>FOLDER_NAME</name>
          <description>Please enter Linux folder name to list</description>
          <value>/var/log</value>
        </hudson.model.StringParameterValue>
      </parameters>
      <parameterDefinitionNames>
        <string>FOLDER_NAME</string>
      </parameterDefinitionNames>
    </hudson.model.ParametersAction>
    <hudson.model.CauseAction>
      <causeBag class="linked-hash-map">
        <entry>
          <hudson.model.Cause_-UserIdCause>
            <userId>lex</userId>
          </hudson.model.Cause_-UserIdCause>
          <int>1</int>
        </entry>
      </causeBag>
    </hudson.model.CauseAction>
  </actions>
  <queueId>70</queueId>
  <timestamp>1628562016897</timestamp>
  <startTime>1628562016907</startTime>
  <result>SUCCESS</result>
  <duration>228</duration>
  <charset>UTF-8</charset>
  <keepLog>false</keepLog>
  <builtOn>ansible-master</builtOn>
  <workspace>/root/jenkins/workspace/Parametr</workspace>
  <hudsonVersion>2.289.3</hudsonVersion>
  <scm class="hudson.scm.NullChangeLogParser"/>
  <culprits class="com.google.common.collect.EmptyImmutableSortedSet"/>
</build>